### PR TITLE
Use google/cadvisor official binary and add support to select cadvisor version

### PR DESCRIPTION
**Pull request by lborguetti**
Guys, 

First, thanks to awesome job with this role. 

This MR allow to select cadvisor version with ansible variables and change to use official google/cadvisor binary.

Thanks,

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks for the suggestion, @lborguetti. We'll look into if the newer cadvisor version will cover our use case. If not, we'll need to have default value rolled back to our expected URL since this is primarily for internal use.

While we do that, can you take a look at the travis failure?

```
ERROR: Idempotence test failed because of the following tasks:
ERROR: * [cadvisor] => ansible-role-cadvisor : cadvisor | enable and start server systemd
```

**Comment by lborguetti** [comment]
@joshmoore If newer cadvisor doesn't cover your case, maybe we can move your expected URL onto default variable, this way I can change the URL select variable like the cadvisor version. 

About travis failure I'll take a look. 

Thanks.

**Comment by lborguetti** [comment]
@joshmoore the test ran locally, https://gist.github.com/lborguetti/38df671cfcc6adafdf0b64edee79b250

My environment:

```shell
Fedora 27
ansible, version: 2.3.1.0
molecule, version: 1.25.0
```
I'll need more time to check this failure. =)

**Comment by manics** [comment]
It might be a Docker on Travis bug https://github.com/openmicroscopy/ansible-role-docker/pull/4

Can you add `docker_version: 17.09.1.ce-1.el7.centos` to the test playbook and see if that gets it passing on Travis?

**Comment by lborguetti** [comment]
@manics I added, but test has failed again. Actually I'm not sure if I did it the right way.

**Comment by lborguetti** [comment]
I made a double check whit the role running in my workstation. 
```
playbook local.yml
- hosts: localhost
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - ansible-role-cadvisor
```

result: https://gist.github.com/lborguetti/4160f6ec24d2f648c57ae0c69930d6d0

Idempotence test sound's good. 

I'll keep debugging ...

**Comment by joshmoore** [comment]
With the recent interest by @Miouge1 in gh-3, I'm going to close and re-open so that travis is retested. If anyone has an idea how to make this go green, let us know.

**Comment by joshmoore** [comment]
Sadly still red @Miouge1 and @lborguetti

**Comment by manics** [comment]
I think this is caused by a change to cadvisor that prevents it running on docker-in-docker which is required for the molecule tests https://github.com/google/cadvisor/issues/1943
```
$ molecule test
...
$ molecule login
```
```
# journalctl -u cadvisor

Jul 31 09:52:35 5adf085cac94 systemd[1]: Started Cadvisor Server.
Jul 31 09:52:35 5adf085cac94 systemd[1]: Starting Cadvisor Server...
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: F0731 09:52:36.054878     492 cadvis
or.go:135] Failed to create a Container Manager: mountpoint for cpu not found
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: goroutine 1 [running]:
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: github.com/google/cadvisor/vendor/gi
thub.com/golang/glog.stacks(0xc42049ce00, 0xc4204600a0, 0x72, 0xa0)
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: /usr/local/google/home/dashpole/go/s
rc/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:769 +0xcf
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: github.com/google/cadvisor/vendor/gi
thub.com/golang/glog.(*loggingT).output(0x15be680, 0xc400000003, 0xc420228000, 0
x12d5f8e, 0xb, 0x87, 0x0)
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: /usr/local/google/home/dashpole/go/s
rc/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:720 +0x345
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: github.com/google/cadvisor/vendor/gi
thub.com/golang/glog.(*loggingT).printf(0x15be680, 0xc400000003, 0xe16497, 0x28,
 0xc4203c1e90, 0x1, 0x1)
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: /usr/local/google/home/dashpole/go/s
rc/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:655 +0x14c
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: github.com/google/cadvisor/vendor/gi
thub.com/golang/glog.Fatalf(0xe16497, 0x28, 0xc4203c1e90, 0x1, 0x1)
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: /usr/local/google/home/dashpole/go/s
rc/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:1148 +0x67
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: main.main()
Jul 31 09:52:36 5adf085cac94 cadvisor[492]: /usr/local/google/home/dashpole/go/s
rc/github.com/google/cadvisor/cadvisor.go:135 +0x27f
Jul 31 09:52:36 5adf085cac94 systemd[1]: cadvisor.service: main process ex
ited, code=exited, status=255/n/a
Jul 31 09:52:36 5adf085cac94 systemd[1]: Unit cadvisor.service entered fai
led state.
Jul 31 09:52:36 5adf085cac94 systemd[1]: cadvisor.service failed.
```
Since this is a `simple` (non-forking) systemd service it's not possible to return an error if `systemctl start` fails, leading to the idempotence error when you attempt to start it again.

Running this with the vagrant driver shows a style (ansible-lint) error in `molecule.yml` but everything else looks OK:
```
$ molecule test --destroy never --driver vagrant
...
--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
ERROR: Trailing newline found at the end of ./molecule.yml.

```

**Comment by Miouge1** [comment]
I got this working with `driver: docker`:
- Add the `volume_mounts: [/sys/fs/cgroup:/sys/fs/cgroup:ro]`: https://github.com/Miouge1/ansible-role-cadvisor/commit/1d51e499cc09ae0b43929b1fd4db5824c764d095
- drop 8d69ad1651bca4bb5f6b073be15bf347a980a245 and 934d6efcf5677b2a9f3249d832f37e5c5be470a2

See https://github.com/Miouge1/ansible-role-cadvisor/pull/2 for an example and https://travis-ci.com/Miouge1/ansible-role-cadvisor/builds/80548024 for the result

**Comment by lborguetti** [comment]
@Miouge1 nice! 

I'll apply the changes in this PR.

**Comment by lborguetti** [comment]
Done! 

@joshmoore can you trigger CI again? thanks

**Comment by joshmoore** [comment]
Sure thing.

**Comment by manics** [comment]
@lborguetti Did you forget to push the changes?

**Comment by lborguetti** [comment]
@manics sorry. I made a mistake. Now I fixed into correct repository.

**Comment by lborguetti** [comment]
@joshmoore Travis running ok now! =)

**Comment by joshmoore** [comment]
Running locally with vagrant:

```
RUNNING HANDLER [ansible-role-cadvisor : reload systemd] ***********************
changed: [cadvisor]

RUNNING HANDLER [ansible-role-cadvisor : restart cadvisor] *********************
changed: [cadvisor]

TASK [ansible-role-cadvisor : cadvisor | enable and start server systemd] ******
changed: [cadvisor]

PLAY RECAP *********************************************************************
cadvisor                   : ok=8    changed=7    unreachable=0    failed=0

--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
[ANSIBLE0006] systemctl used in place of systemd module
/opt/own-ansible/ansible-role-cadvisor/handlers/main.yml:4
Task/Handler: reload systemd
```

**Comment by joshmoore** [comment]
```
TASK [ansible-role-cadvisor : cadvisor | enable and start server systemd] ******
changed: [cadvisor]

PLAY RECAP *********************************************************************
cadvisor                   : ok=8    changed=7    unreachable=0    failed=0

--> Idempotence test in progress (can take a few minutes)...
--> Starting Ansible Run...
Idempotence test passed.
--> Executing ansible-lint...
[ANSIBLE0006] systemctl used in place of systemd module
/opt/own-ansible/ansible-role-cadvisor/handlers/main.yml:4
Task/Handler: reload systemd
```

on

screen shot 2018-08-09 at 11 16 54


Releasing as `0.2.0`

**Comment by joshmoore** [comment]
Thanks, all!

**Pull request merged**
